// Code generated by hertz generator.

package main

import (
	"github.com/xh-polaris/meowchat-core-api/biz/infrastructure/obs/log"
	"github.com/xh-polaris/meowchat-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app/server"
	"go.opentelemetry.io/contrib/propagators/b3"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
)

func Init() {
	log.Init()
	provider.Init()
}

func main() {
	Init()
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(b3.New(), propagation.Baggage{}, propagation.TraceContext{}))
	h := server.Default()
	register(h)
	h.Spin()
}
