// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"github.com/xh-polaris/meowchat-core-api/biz/infrastructure/obs/log"
	"github.com/xh-polaris/meowchat-core-api/biz/infrastructure/obs/trace"
	"github.com/xh-polaris/meowchat-core-api/provider"
)

func Init() {
	provider.Init()
	log.Init()
	trace.Init()
}

func main() {
	Init()
	c := provider.Get().Config
	log.SetLevel(c.LogLevel)
	h := server.Default(
		server.WithHostPorts(c.ListenOn),
	)
	register(h)
	log.Info("server start")
	h.Spin()
}
