// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/xh-polaris/meowchat-core-api/biz/adaptor"
	"github.com/xh-polaris/meowchat-core-api/biz/application/dto/meowchat/core_api"
	"github.com/xh-polaris/meowchat-core-api/provider"
)

// CheckIn .
// @router /incentive/check_in [GET]
func CheckIn(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CheckInReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.IncentiveService.CheckIn(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetMission .
// @router /incentive/get_mission [GET]
func GetMission(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetMissionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.IncentiveService.GetMission(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
