// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/meowchat-core-api/biz/adaptor"
	"github.com/xh-polaris/meowchat-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	core_api "github.com/xh-polaris/meowchat-core-api/biz/application/dto/meowchat/core_api"
)

// GetAdmins .
// @router /notice/get_admins [GET]
func GetAdmins(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetAdminsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.GetAdmins(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// NewAdmin .
// @router /notice/new_admin [POST]
func NewAdmin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.NewAdminReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.NewAdmin(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// DeleteAdmin .
// @router /notice/delete_admin [POST]
func DeleteAdmin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteAdminReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.DeleteAdmin(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// ListApply .
// @router /notice/list_apply [POST]
func ListApply(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListApplyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.ListApply(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// HandleApply .
// @router /notice/handle_apply [POST]
func HandleApply(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.HandleApplyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.HandleApply(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// GetNews .
// @router /notice/get_news [GET]
func GetNews(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetNewsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.GetNews(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// NewNews .
// @router /notice/new_news [POST]
func NewNews(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.NewNewsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.NewNews(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// DeleteNews .
// @router /notice/remove_news [POST]
func DeleteNews(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteNewsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.DeleteNews(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// GetNotices .
// @router /notice/get_notices [GET]
func GetNotices(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetNoticesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.GetNotices(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// NewNotice .
// @router /notice/new_notice [POST]
func NewNotice(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.NewNoticeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.NewNotice(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// DeleteNotice .
// @router /notice/remove_notice [POST]
func DeleteNotice(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteNoticeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.DeleteNotice(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// ListCommunity .
// @router /community/list_community [GET]
func ListCommunity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListCommunityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.ListCommunity(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// NewCommunity .
// @router /community/new_community [POST]
func NewCommunity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.NewCommunityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.NewCommunity(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// DeleteCommunity .
// @router /community/delete_community [POST]
func DeleteCommunity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteCommunityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.DeleteCommunity(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// GetUserRoles .
// @router /role/get_user_roles [GET]
func GetUserRoles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetUserRolesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.GetUserRoles(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// UpdateCommunityAdmin .
// @router /role/update_community_admin [POST]
func UpdateCommunityAdmin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UpdateCommunityAdminReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.UpdateCommunityAdmin(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// UpdateSuperAdmin .
// @router /role/update_super_admin [POST]
func UpdateSuperAdmin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UpdateSuperAdminReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.UpdateSuperAdmin(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// GetUserByRole .
// @router /role/get_user_by_role [GET]
func GetUserByRole(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.RetrieveUserPreviewReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.GetUserByRole(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}

// CreateApply .
// @router /role/create_apply [POST]
func CreateApply(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateApplyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.CreateApply(ctx, &req)
	adaptor.Return(ctx, c, &req, resp, err)
}
