// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.23.4
// source: meowchat/core_api/plan.proto

package core_api

import (
	basic "github.com/xh-polaris/meowchat-core-api/biz/application/dto/basic"
	content "github.com/xh-polaris/meowchat-core-api/biz/application/dto/meowchat/content"
	user "github.com/xh-polaris/meowchat-core-api/biz/application/dto/meowchat/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	Name        string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	Description string              `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty" form:"description" query:"description"`
	PlanType    content.PlanType    `protobuf:"varint,4,opt,name=planType,proto3,enum=meowchat.content.PlanType" json:"planType,omitempty" form:"planType" query:"planType"`
	StartTime   int64               `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty" form:"startTime" query:"startTime"`
	EndTime     int64               `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty" form:"endTime" query:"endTime"`
	CatId       string              `protobuf:"bytes,7,opt,name=catId,proto3" json:"catId,omitempty" form:"catId" query:"catId"`
	Users       []*user.UserPreview `protobuf:"bytes,8,rep,name=users,proto3" json:"users,omitempty" form:"users" query:"users"`
	ImageUrls   []string            `protobuf:"bytes,9,rep,name=imageUrls,proto3" json:"imageUrls,omitempty" form:"imageUrls" query:"imageUrls"`
	CreateAt    int64               `protobuf:"varint,10,opt,name=createAt,proto3" json:"createAt,omitempty" form:"createAt" query:"createAt"`
	MaxFish     int64               `protobuf:"varint,11,opt,name=maxFish,proto3" json:"maxFish,omitempty" form:"maxFish" query:"maxFish"`
	NowFish     int64               `protobuf:"varint,12,opt,name=nowFish,proto3" json:"nowFish,omitempty" form:"nowFish" query:"nowFish"`
}

func (x *Plan) Reset() {
	*x = Plan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPlanType() content.PlanType {
	if x != nil {
		return x.PlanType
	}
	return content.PlanType(0)
}

func (x *Plan) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Plan) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Plan) GetCatId() string {
	if x != nil {
		return x.CatId
	}
	return ""
}

func (x *Plan) GetUsers() []*user.UserPreview {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Plan) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Plan) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Plan) GetMaxFish() int64 {
	if x != nil {
		return x.MaxFish
	}
	return 0
}

func (x *Plan) GetNowFish() int64 {
	if x != nil {
		return x.NowFish
	}
	return 0
}

type GetPlanPreviewsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId            *string                  `protobuf:"bytes,1,opt,name=catId,proto3,oneof" json:"catId,omitempty" form:"catId" query:"catId"`
	OnlyUserId       *string                  `protobuf:"bytes,2,opt,name=onlyUserId,proto3,oneof" json:"onlyUserId,omitempty" form:"onlyUserId" query:"onlyUserId"`
	PaginationOption *basic.PaginationOptions `protobuf:"bytes,3,opt,name=paginationOption,proto3" json:"paginationOption,omitempty" form:"paginationOption" query:"paginationOption"`
}

func (x *GetPlanPreviewsReq) Reset() {
	*x = GetPlanPreviewsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanPreviewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanPreviewsReq) ProtoMessage() {}

func (x *GetPlanPreviewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanPreviewsReq.ProtoReflect.Descriptor instead.
func (*GetPlanPreviewsReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlanPreviewsReq) GetCatId() string {
	if x != nil && x.CatId != nil {
		return *x.CatId
	}
	return ""
}

func (x *GetPlanPreviewsReq) GetOnlyUserId() string {
	if x != nil && x.OnlyUserId != nil {
		return *x.OnlyUserId
	}
	return ""
}

func (x *GetPlanPreviewsReq) GetPaginationOption() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOption
	}
	return nil
}

type GetPlanPreviewsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plans []*Plan `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty" form:"plans" query:"plans"`
	Total int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" form:"total" query:"total"`
	Token string  `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty" form:"token" query:"token"`
}

func (x *GetPlanPreviewsResp) Reset() {
	*x = GetPlanPreviewsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanPreviewsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanPreviewsResp) ProtoMessage() {}

func (x *GetPlanPreviewsResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanPreviewsResp.ProtoReflect.Descriptor instead.
func (*GetPlanPreviewsResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlanPreviewsResp) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *GetPlanPreviewsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPlanPreviewsResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPlanDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId string `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty" form:"planId" query:"planId"`
}

func (x *GetPlanDetailReq) Reset() {
	*x = GetPlanDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanDetailReq) ProtoMessage() {}

func (x *GetPlanDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanDetailReq.ProtoReflect.Descriptor instead.
func (*GetPlanDetailReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlanDetailReq) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type GetPlanDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plan *Plan `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty" form:"plan" query:"plan"`
}

func (x *GetPlanDetailResp) Reset() {
	*x = GetPlanDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanDetailResp) ProtoMessage() {}

func (x *GetPlanDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanDetailResp.ProtoReflect.Descriptor instead.
func (*GetPlanDetailResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlanDetailResp) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type DeletePlanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId string `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty" form:"planId" query:"planId"`
}

func (x *DeletePlanReq) Reset() {
	*x = DeletePlanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanReq) ProtoMessage() {}

func (x *DeletePlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanReq.ProtoReflect.Descriptor instead.
func (*DeletePlanReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePlanReq) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type DeletePlanResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePlanResp) Reset() {
	*x = DeletePlanResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanResp) ProtoMessage() {}

func (x *DeletePlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanResp.ProtoReflect.Descriptor instead.
func (*DeletePlanResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{6}
}

type NewPlanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *string           `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty" form:"id" query:"id"`
	Name        *string           `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty" form:"name" query:"name"`
	Description *string           `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty" form:"description" query:"description"`
	PlanType    *content.PlanType `protobuf:"varint,4,opt,name=planType,proto3,enum=meowchat.content.PlanType,oneof" json:"planType,omitempty" form:"planType" query:"planType"`
	StartTime   *int64            `protobuf:"varint,5,opt,name=startTime,proto3,oneof" json:"startTime,omitempty" form:"startTime" query:"startTime"`
	EndTime     *int64            `protobuf:"varint,6,opt,name=endTime,proto3,oneof" json:"endTime,omitempty" form:"endTime" query:"endTime"`
	CatId       *string           `protobuf:"bytes,7,opt,name=catId,proto3,oneof" json:"catId,omitempty" form:"catId" query:"catId"`
	MaxFish     *int64            `protobuf:"varint,8,opt,name=maxFish,proto3,oneof" json:"maxFish,omitempty" form:"maxFish" query:"maxFish"`
	ImageUrls   []string          `protobuf:"bytes,9,rep,name=imageUrls,proto3" json:"imageUrls,omitempty" form:"imageUrls" query:"imageUrls"`
}

func (x *NewPlanReq) Reset() {
	*x = NewPlanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPlanReq) ProtoMessage() {}

func (x *NewPlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPlanReq.ProtoReflect.Descriptor instead.
func (*NewPlanReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{7}
}

func (x *NewPlanReq) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *NewPlanReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NewPlanReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *NewPlanReq) GetPlanType() content.PlanType {
	if x != nil && x.PlanType != nil {
		return *x.PlanType
	}
	return content.PlanType(0)
}

func (x *NewPlanReq) GetStartTime() int64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *NewPlanReq) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *NewPlanReq) GetCatId() string {
	if x != nil && x.CatId != nil {
		return *x.CatId
	}
	return ""
}

func (x *NewPlanReq) GetMaxFish() int64 {
	if x != nil && x.MaxFish != nil {
		return *x.MaxFish
	}
	return 0
}

func (x *NewPlanReq) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type NewPlanResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId string `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty" form:"planId" query:"planId"`
}

func (x *NewPlanResp) Reset() {
	*x = NewPlanResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPlanResp) ProtoMessage() {}

func (x *NewPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPlanResp.ProtoReflect.Descriptor instead.
func (*NewPlanResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{8}
}

func (x *NewPlanResp) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type SearchPlanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId            *string                  `protobuf:"bytes,1,opt,name=catId,proto3,oneof" json:"catId,omitempty" form:"catId" query:"catId"`
	OnlyUserId       *string                  `protobuf:"bytes,3,opt,name=onlyUserId,proto3,oneof" json:"onlyUserId,omitempty" form:"onlyUserId" query:"onlyUserId"`
	Keyword          *string                  `protobuf:"bytes,4,opt,name=keyword,proto3,oneof" json:"keyword,omitempty" form:"keyword" query:"keyword"`
	PaginationOption *basic.PaginationOptions `protobuf:"bytes,5,opt,name=paginationOption,proto3" json:"paginationOption,omitempty" form:"paginationOption" query:"paginationOption"`
}

func (x *SearchPlanReq) Reset() {
	*x = SearchPlanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlanReq) ProtoMessage() {}

func (x *SearchPlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlanReq.ProtoReflect.Descriptor instead.
func (*SearchPlanReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{9}
}

func (x *SearchPlanReq) GetCatId() string {
	if x != nil && x.CatId != nil {
		return *x.CatId
	}
	return ""
}

func (x *SearchPlanReq) GetOnlyUserId() string {
	if x != nil && x.OnlyUserId != nil {
		return *x.OnlyUserId
	}
	return ""
}

func (x *SearchPlanReq) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *SearchPlanReq) GetPaginationOption() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOption
	}
	return nil
}

type SearchPlanResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plans []*Plan `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty" form:"plans" query:"plans"`
	Total int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" form:"total" query:"total"`
}

func (x *SearchPlanResp) Reset() {
	*x = SearchPlanResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlanResp) ProtoMessage() {}

func (x *SearchPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlanResp.ProtoReflect.Descriptor instead.
func (*SearchPlanResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{10}
}

func (x *SearchPlanResp) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *SearchPlanResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DonateFishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId string `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty" form:"planId" query:"planId"`
	Fish   int64  `protobuf:"varint,2,opt,name=fish,proto3" json:"fish,omitempty" form:"fish" query:"fish"`
}

func (x *DonateFishReq) Reset() {
	*x = DonateFishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonateFishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonateFishReq) ProtoMessage() {}

func (x *DonateFishReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonateFishReq.ProtoReflect.Descriptor instead.
func (*DonateFishReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{11}
}

func (x *DonateFishReq) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *DonateFishReq) GetFish() int64 {
	if x != nil {
		return x.Fish
	}
	return 0
}

type DonateFishResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DonateFishResp) Reset() {
	*x = DonateFishResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonateFishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonateFishResp) ProtoMessage() {}

func (x *DonateFishResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonateFishResp.ProtoReflect.Descriptor instead.
func (*DonateFishResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{12}
}

type GetUserFishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *string `protobuf:"bytes,1,opt,name=userId,proto3,oneof" json:"userId,omitempty" form:"userId" query:"userId"`
}

func (x *GetUserFishReq) Reset() {
	*x = GetUserFishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserFishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFishReq) ProtoMessage() {}

func (x *GetUserFishReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFishReq.ProtoReflect.Descriptor instead.
func (*GetUserFishReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserFishReq) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type GetUserFishResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fish int64 `protobuf:"varint,1,opt,name=fish,proto3" json:"fish,omitempty" form:"fish" query:"fish"`
}

func (x *GetUserFishResp) Reset() {
	*x = GetUserFishResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserFishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFishResp) ProtoMessage() {}

func (x *GetUserFishResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFishResp.ProtoReflect.Descriptor instead.
func (*GetUserFishResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserFishResp) GetFish() int64 {
	if x != nil {
		return x.Fish
	}
	return 0
}

type ListFishByPlanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId string `protobuf:"bytes,1,opt,name=planId,proto3" json:"planId,omitempty" form:"planId" query:"planId"`
}

func (x *ListFishByPlanReq) Reset() {
	*x = ListFishByPlanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFishByPlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFishByPlanReq) ProtoMessage() {}

func (x *ListFishByPlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFishByPlanReq.ProtoReflect.Descriptor instead.
func (*ListFishByPlanReq) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{15}
}

func (x *ListFishByPlanReq) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type ListFishByPlanResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users   []*user.UserPreview `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" form:"users" query:"users"`
	FishMap map[string]int64    `protobuf:"bytes,2,rep,name=fishMap,proto3" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" json:"fishMap,omitempty" form:"fishMap" query:"fishMap"`
}

func (x *ListFishByPlanResp) Reset() {
	*x = ListFishByPlanResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_core_api_plan_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFishByPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFishByPlanResp) ProtoMessage() {}

func (x *ListFishByPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_core_api_plan_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFishByPlanResp.ProtoReflect.Descriptor instead.
func (*ListFishByPlanResp) Descriptor() ([]byte, []int) {
	return file_meowchat_core_api_plan_proto_rawDescGZIP(), []int{16}
}

func (x *ListFishByPlanResp) GetUsers() []*user.UserPreview {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListFishByPlanResp) GetFishMap() map[string]int64 {
	if x != nil {
		return x.FishMap
	}
	return nil
}

var File_meowchat_core_api_plan_proto protoreflect.FileDescriptor

var file_meowchat_core_api_plan_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x1a, 0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x6d, 0x65, 0x6f, 0x77, 0x63,
	0x68, 0x61, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf2, 0x02, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x73, 0x68,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x73, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x77, 0x46, 0x69, 0x73, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x6e, 0x6f, 0x77, 0x46, 0x69, 0x73, 0x68, 0x22, 0xb3, 0x01, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x6e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x19, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x6f,
	0x6e, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x0a, 0x6f, 0x6e, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x44, 0x0a, 0x10, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x10, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x61, 0x74, 0x49, 0x64,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x70, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x05,
	0x70, 0x6c, 0x61, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x40, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2b, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x22,
	0x27, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x95, 0x03, 0x0a, 0x0a, 0x4e,
	0x65, 0x77, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x17,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x3b,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x48, 0x03, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x04,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x05, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a,
	0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x06, 0x52, 0x05,
	0x63, 0x61, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x46,
	0x69, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x48, 0x07, 0x52, 0x07, 0x6d, 0x61, 0x78,
	0x46, 0x69, 0x73, 0x68, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x63, 0x61, 0x74, 0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x61, 0x78, 0x46, 0x69,
	0x73, 0x68, 0x22, 0x25, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0xd9, 0x01, 0x0a, 0x0d, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x05, 0x63,
	0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x63, 0x61,
	0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x6f, 0x6e, 0x6c, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x6f, 0x6e,
	0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01, 0x12, 0x44, 0x0a, 0x10, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x10,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x61, 0x74, 0x49, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6f,
	0x6e, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x55, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50,
	0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52,
	0x05, 0x70, 0x6c, 0x61, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x3b, 0x0a, 0x0d,
	0x44, 0x6f, 0x6e, 0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x69, 0x73, 0x68, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x6f, 0x6e,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x38, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x69, 0x73, 0x68, 0x22, 0x2b, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x73, 0x68, 0x42, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0xd0, 0x01, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x69, 0x73, 0x68, 0x42, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x30, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x12, 0x4c, 0x0a, 0x07, 0x66, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x70, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x73, 0x68,
	0x42, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x46, 0x69, 0x73, 0x68, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x66, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x70,
	0x1a, 0x3a, 0x0a, 0x0c, 0x46, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x83, 0x01, 0x0a,
	0x25, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x68, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2e, 0x69,
	0x64, 0x6c, 0x67, 0x65, 0x6e, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x61, 0x70, 0x69, 0x42, 0x09, 0x50, 0x6c, 0x61, 0x6e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x63,
	0x68, 0x61, 0x74, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a,
	0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x74, 0x6f,
	0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meowchat_core_api_plan_proto_rawDescOnce sync.Once
	file_meowchat_core_api_plan_proto_rawDescData = file_meowchat_core_api_plan_proto_rawDesc
)

func file_meowchat_core_api_plan_proto_rawDescGZIP() []byte {
	file_meowchat_core_api_plan_proto_rawDescOnce.Do(func() {
		file_meowchat_core_api_plan_proto_rawDescData = protoimpl.X.CompressGZIP(file_meowchat_core_api_plan_proto_rawDescData)
	})
	return file_meowchat_core_api_plan_proto_rawDescData
}

var file_meowchat_core_api_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_meowchat_core_api_plan_proto_goTypes = []interface{}{
	(*Plan)(nil),                    // 0: meowchat.core_api.Plan
	(*GetPlanPreviewsReq)(nil),      // 1: meowchat.core_api.GetPlanPreviewsReq
	(*GetPlanPreviewsResp)(nil),     // 2: meowchat.core_api.GetPlanPreviewsResp
	(*GetPlanDetailReq)(nil),        // 3: meowchat.core_api.GetPlanDetailReq
	(*GetPlanDetailResp)(nil),       // 4: meowchat.core_api.GetPlanDetailResp
	(*DeletePlanReq)(nil),           // 5: meowchat.core_api.DeletePlanReq
	(*DeletePlanResp)(nil),          // 6: meowchat.core_api.DeletePlanResp
	(*NewPlanReq)(nil),              // 7: meowchat.core_api.NewPlanReq
	(*NewPlanResp)(nil),             // 8: meowchat.core_api.NewPlanResp
	(*SearchPlanReq)(nil),           // 9: meowchat.core_api.SearchPlanReq
	(*SearchPlanResp)(nil),          // 10: meowchat.core_api.SearchPlanResp
	(*DonateFishReq)(nil),           // 11: meowchat.core_api.DonateFishReq
	(*DonateFishResp)(nil),          // 12: meowchat.core_api.DonateFishResp
	(*GetUserFishReq)(nil),          // 13: meowchat.core_api.GetUserFishReq
	(*GetUserFishResp)(nil),         // 14: meowchat.core_api.GetUserFishResp
	(*ListFishByPlanReq)(nil),       // 15: meowchat.core_api.ListFishByPlanReq
	(*ListFishByPlanResp)(nil),      // 16: meowchat.core_api.ListFishByPlanResp
	nil,                             // 17: meowchat.core_api.ListFishByPlanResp.FishMapEntry
	(content.PlanType)(0),           // 18: meowchat.content.PlanType
	(*user.UserPreview)(nil),        // 19: meowchat.user.UserPreview
	(*basic.PaginationOptions)(nil), // 20: basic.PaginationOptions
}
var file_meowchat_core_api_plan_proto_depIdxs = []int32{
	18, // 0: meowchat.core_api.Plan.planType:type_name -> meowchat.content.PlanType
	19, // 1: meowchat.core_api.Plan.users:type_name -> meowchat.user.UserPreview
	20, // 2: meowchat.core_api.GetPlanPreviewsReq.paginationOption:type_name -> basic.PaginationOptions
	0,  // 3: meowchat.core_api.GetPlanPreviewsResp.plans:type_name -> meowchat.core_api.Plan
	0,  // 4: meowchat.core_api.GetPlanDetailResp.plan:type_name -> meowchat.core_api.Plan
	18, // 5: meowchat.core_api.NewPlanReq.planType:type_name -> meowchat.content.PlanType
	20, // 6: meowchat.core_api.SearchPlanReq.paginationOption:type_name -> basic.PaginationOptions
	0,  // 7: meowchat.core_api.SearchPlanResp.plans:type_name -> meowchat.core_api.Plan
	19, // 8: meowchat.core_api.ListFishByPlanResp.users:type_name -> meowchat.user.UserPreview
	17, // 9: meowchat.core_api.ListFishByPlanResp.fishMap:type_name -> meowchat.core_api.ListFishByPlanResp.FishMapEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func file_meowchat_core_api_plan_proto_init() {
	if File_meowchat_core_api_plan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meowchat_core_api_plan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanPreviewsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanPreviewsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlanResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPlanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPlanResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPlanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPlanResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DonateFishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DonateFishResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserFishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserFishResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFishByPlanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_core_api_plan_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFishByPlanResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_meowchat_core_api_plan_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_meowchat_core_api_plan_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_meowchat_core_api_plan_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_meowchat_core_api_plan_proto_msgTypes[13].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meowchat_core_api_plan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meowchat_core_api_plan_proto_goTypes,
		DependencyIndexes: file_meowchat_core_api_plan_proto_depIdxs,
		MessageInfos:      file_meowchat_core_api_plan_proto_msgTypes,
	}.Build()
	File_meowchat_core_api_plan_proto = out.File
	file_meowchat_core_api_plan_proto_rawDesc = nil
	file_meowchat_core_api_plan_proto_goTypes = nil
	file_meowchat_core_api_plan_proto_depIdxs = nil
}
