// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: meowchat/collection/common.proto

package collection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	CreateAt     int64    `protobuf:"varint,2,opt,name=createAt,proto3" json:"createAt,omitempty" form:"createAt" query:"createAt"`
	Age          string   `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty" form:"age" query:"age"`
	CommunityId  string   `protobuf:"bytes,4,opt,name=communityId,proto3" json:"communityId,omitempty" form:"communityId" query:"communityId"`
	Color        string   `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty" form:"color" query:"color"`
	Details      string   `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty" form:"details" query:"details"`
	Name         string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty" form:"name" query:"name"`
	Popularity   int64    `protobuf:"varint,8,opt,name=popularity,proto3" json:"popularity,omitempty" form:"popularity" query:"popularity"`
	Sex          string   `protobuf:"bytes,9,opt,name=sex,proto3" json:"sex,omitempty" form:"sex" query:"sex"`
	Status       int64    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty" form:"status" query:"status"`
	Area         string   `protobuf:"bytes,11,opt,name=area,proto3" json:"area,omitempty" form:"area" query:"area"`
	IsSnipped    bool     `protobuf:"varint,12,opt,name=isSnipped,proto3" json:"isSnipped,omitempty" form:"isSnipped" query:"isSnipped"`
	IsSterilized bool     `protobuf:"varint,13,opt,name=isSterilized,proto3" json:"isSterilized,omitempty" form:"isSterilized" query:"isSterilized"`
	Avatars      []string `protobuf:"bytes,14,rep,name=avatars,proto3" json:"avatars,omitempty" form:"avatars" query:"avatars"`
}

func (x *Cat) Reset() {
	*x = Cat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_collection_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cat) ProtoMessage() {}

func (x *Cat) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_collection_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cat.ProtoReflect.Descriptor instead.
func (*Cat) Descriptor() ([]byte, []int) {
	return file_meowchat_collection_common_proto_rawDescGZIP(), []int{0}
}

func (x *Cat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cat) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Cat) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Cat) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *Cat) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Cat) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Cat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cat) GetPopularity() int64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Cat) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Cat) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Cat) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Cat) GetIsSnipped() bool {
	if x != nil {
		return x.IsSnipped
	}
	return false
}

func (x *Cat) GetIsSterilized() bool {
	if x != nil {
		return x.IsSterilized
	}
	return false
}

func (x *Cat) GetAvatars() []string {
	if x != nil {
		return x.Avatars
	}
	return nil
}

type CreateImageElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId string `protobuf:"bytes,1,opt,name=catId,proto3" json:"catId,omitempty" form:"catId" query:"catId"`
	Url   string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty" form:"url" query:"url"`
}

func (x *CreateImageElement) Reset() {
	*x = CreateImageElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_collection_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateImageElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageElement) ProtoMessage() {}

func (x *CreateImageElement) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_collection_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageElement.ProtoReflect.Descriptor instead.
func (*CreateImageElement) Descriptor() ([]byte, []int) {
	return file_meowchat_collection_common_proto_rawDescGZIP(), []int{1}
}

func (x *CreateImageElement) GetCatId() string {
	if x != nil {
		return x.CatId
	}
	return ""
}

func (x *CreateImageElement) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" form:"id" query:"id"`
	Url   string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty" form:"url" query:"url"`
	CatId string `protobuf:"bytes,3,opt,name=catId,proto3" json:"catId,omitempty" form:"catId" query:"catId"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meowchat_collection_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_meowchat_collection_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_meowchat_collection_common_proto_rawDescGZIP(), []int{2}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetCatId() string {
	if x != nil {
		return x.CatId
	}
	return ""
}

var File_meowchat_collection_common_proto protoreflect.FileDescriptor

var file_meowchat_collection_common_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x13, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe3, 0x02, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x69, 0x73, 0x53, 0x74, 0x65, 0x72, 0x69, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x53, 0x74, 0x65, 0x72, 0x69, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x18, 0x0e,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x22, 0x3c, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3f, 0x0a, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x42, 0x51, 0x5a, 0x4f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f,
	0x6c, 0x61, 0x72, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2d, 0x63,
	0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6f, 0x77,
	0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meowchat_collection_common_proto_rawDescOnce sync.Once
	file_meowchat_collection_common_proto_rawDescData = file_meowchat_collection_common_proto_rawDesc
)

func file_meowchat_collection_common_proto_rawDescGZIP() []byte {
	file_meowchat_collection_common_proto_rawDescOnce.Do(func() {
		file_meowchat_collection_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_meowchat_collection_common_proto_rawDescData)
	})
	return file_meowchat_collection_common_proto_rawDescData
}

var file_meowchat_collection_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meowchat_collection_common_proto_goTypes = []interface{}{
	(*Cat)(nil),                // 0: meowchat.collection.Cat
	(*CreateImageElement)(nil), // 1: meowchat.collection.CreateImageElement
	(*Image)(nil),              // 2: meowchat.collection.Image
}
var file_meowchat_collection_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meowchat_collection_common_proto_init() }
func file_meowchat_collection_common_proto_init() {
	if File_meowchat_collection_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meowchat_collection_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_collection_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateImageElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meowchat_collection_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meowchat_collection_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meowchat_collection_common_proto_goTypes,
		DependencyIndexes: file_meowchat_collection_common_proto_depIdxs,
		MessageInfos:      file_meowchat_collection_common_proto_msgTypes,
	}.Build()
	File_meowchat_collection_common_proto = out.File
	file_meowchat_collection_common_proto_rawDesc = nil
	file_meowchat_collection_common_proto_goTypes = nil
	file_meowchat_collection_common_proto_depIdxs = nil
}
