// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _collectionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcatdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcatpreviewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getimagebycatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newcatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchcatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dolikeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlikedcountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlikedusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserlikedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserlikesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _momentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemomentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmomentdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmomentpreviewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newmomentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchmomentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostpreviewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setofficialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applysignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applysignedurlascommunityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchuserforadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _communityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommunityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcommunityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newcommunityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _noticeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getadminsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoticesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handleapplyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listapplyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newnewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newnoticeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletenewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletenoticeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbyroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserrolesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecommunityadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesuperadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createapplyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateroleMw() []app.HandlerFunc {
	// your code...
	return nil
}
